# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# Build version format
version: "{build}"

clone_depth: 10

# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

# What combinations to test
environment:
  matrix:
    - nodejs_version: 0.12
    - nodejs_version: 4

install:
  - cmd: npm -v
  - cmd: node -v
  - cmd: npm install -g gulp
  - cmd: npm install

build: off

build_script:
  - gulp init

test_script:
  - cmd: gulp build --release --ie
